FROM python:3.10-slim
WORKDIR /app

# --- เพิ่มส่วนนี้เพื่อติดตั้งเครื่องมือพื้นฐานที่ bcrypt ต้องใช้ ---
RUN apt-get update && apt-get install -y gcc libffi-dev python3-dev libpq-dev && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]